language: c++

compiler:
 - gcc
 - clang

script:
 - qmake -project
 - qmake kakapos.pro QT+=widgets
 - make

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5	; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew linkapps qt5 ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt5-default qttools5-dev-tools ; fi
os:
 - osx
 # - linux
