install:
  - set QTDIR=C:\Qt\5.9.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake kakapos.pro
  - mingw32-make
  - mkdir kakapos-0.5.5
  - mv kakapos.exe kakapos-0.5.5
  - cd kakapos-0.5.5
  - windeployqt kakapos.exe
  - cd ..
artifacts:
  - path: kakapos-0.5.5
deploy:
  - provider: GitHub
      artifact: /.*\.zip/           # upload all NuGet packages to release assets
      draft: false
      prerelease: true
      on:
        branch: master                # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only
